### ISSUE TITLE
Одновременный поиск по нескольким поисковикам

### ISSUE THREAD

**Issue by OmlineEditor** [hyoo-ru/search.hyoo.ru#12]
сейчас поиск выдает 10 результатов и нет возможности перейти на 2ю страницу если не получилось найти нужный результат, можно ли сделать 30 строк в результатах, по 10 строк на каждый поисковик, 10 на результат от google, 10 от яндекса и 10 строк от поисковика duckduckgo. это максимально широкий результата поиска по нескольким поисковикам

**Comment by nin-jin** [comment]
Сейчас выводится 20 результатов из Гугла.
Другие поисковики не предоставляют бесплатного апи, через которое можно было бы это осуществить.
Но даже если бы и можно было искать по нескольким поисковикам, не понятно в каком порядке сливать их результаты.

**Comment by OmlineEditor** [comment]
> не понятно в каком порядке сливать их результаты.

N строка в поиске гугла это 3*N-2 строка в результате у вас
N строка в поиске яндекса это 3*N-1 строка в результате у вас
N строка в поиске duckduckgo это 3*N строка в результате у вас

Надеюсь появится API, попробуйте написать им техническим языком чтобы они добавили API. Если нужно давайте создадим шаблон для письма и напишем все вместе им.

**Comment by nin-jin** [comment]
У них нет никакой мотивации делать отдельное апи для конкурентов.

**Comment by OmlineEditor** [comment]
Возможно вы правы, но если надумаете что-то сделать, например написать письмо им или начнете голосование по созданию API, дайте мне знать. чем смогу - тем помогу.

**Comment by nin-jin** [comment]
А вы на чём специализируетесь? Лучше время потратить на чо-то менее бесперспективное.

**Comment by OmlineEditor** [comment]
Я блондинка от меня будет мало толку как разработчик. Но я просто упрямая как слон, буду вас морально поддерживать и писать петиции для поддержки и еще говорить друзьям чтобы они вас поддерживали. вот как-то так :-)

**Comment by nin-jin** [comment]
Это-то понятно. А по жизни чем занимаетесь? Нам бы как-то продвинуть [гильдию](https://offer.hyoo.ru/), найти спонсоров на [проекты](https://apps.hyoo.ru/) или типа того. Мы периодически участвуем в [хакатонах](https://www.youtube.com/playlist?list=PLXyFFhv8ucKTqaavXRjOCFNqoIzgdFdrN), готовим [презентации](https://docs.google.com/presentation/d/18UKSwM0I55RqzlmJzTU7UDTmFlHIiJdcoYJRtE2jLpU/edit#slide=id.p). Но походить по инвесторам, попитчить им идеи всё руки не доходят.

**Comment by OmlineEditor** [comment]
Могу в магните на кассе предлагать ваши визитки, но я думаю бабульке что купила пачку молока будет мало интересно смотреть ваши проекты. И с меня спонсор будет никакущий. Своло "хакатон" для меня как ругательство т.к. незнаю что это.
Давайте вернется к поиску по нескольким сайтам и API. Может хотя бы написать письмо в яндекс и duckduckgo?
Дайте текст письма на вашем научном языке я напишу, спрошу что нужно? Может ответят

**Comment by nin-jin** [comment]
С тем же успехом можно писать письма в спортлото.

**Comment by OmlineEditor** [comment]
> С тем же успехом можно писать письма в спортлото.
![Personnages-celebres-Troll-face-Okay-meme-face-145305](https://user-images.githubusercontent.com/13348933/126070859-3f542f4d-49fe-4986-a299-4c8d254e0deb.png)



Ну тогда закрывайте тикет
