### ISSUE TITLE
не видно иконки в низу страницы

### ISSUE THREAD

**Issue by OmlineEditor** [hyoo-ru/search.hyoo.ru#13]
в низу страницы есть кнопки или иконки для перехода в другой поисковик, но эти иконки не видно, они не отображаются
сделайте их ближе друг к другу и сделаейте видимыми.

![изображение_2021-07-14_161820](https://user-images.githubusercontent.com/13348933/125628715-e6b2af4f-8b13-41e2-ad51-4e3cf38c1949.png)

**Comment by nin-jin** [comment]
Иконки должны отображаться. Можете открыть консоль (Ctrl+Shift+I или Cmd+Shift+I) и прислать её скриншот?

**Comment by OmlineEditor** [comment]
Вот консоль:

![изображение_2021-07-14_175536](https://user-images.githubusercontent.com/13348933/125643952-541c8378-cf07-49c2-b5f7-4184fbe137dc.png)

**Comment by nin-jin** [comment]
Затрудняюсь сказать в чём дело. Может быть блокировщики рекламы или иные расширения браузера виноваты?

**Comment by OmlineEditor** [comment]
не думаю, я выключала блокировщик и результат тот же. Может это не Ublock.
Если это просто иконки что стороннего сайта, может эти иконки (или картинки) перенести на свой сайт и брать с него, а не со стороннего сайта чтобы ничего не блочилось?

**Comment by nin-jin** [comment]
Эти иконки подтягиваются с Яндекса используя домены, указанные [тут](https://github.com/hyoo-ru/search.hyoo.ru/issues/11). Заранее задать иконки, соответственно, не представляется возможным.

**Comment by nin-jin** [comment]
А что если попробовать открыть через VPN ли в анонимной вкладке?

**Comment by OmlineEditor** [comment]
заработало, иконки появились. Что-то у меня на компе блочит или провайдер такой. Пока не могу понять где проблема, но похоже проблема только у меня.
Скажите иконки можно сгрупировать поближе друг к другу и в центре расположить и не размазывать их по всей нижней части?
![изображение_2021-07-17_014949](https://user-images.githubusercontent.com/13348933/126015510-dad9e4ed-53a8-4b25-b508-034821365f6e.png)

**Comment by nin-jin** [comment]
А зачем их кучковать?

**Comment by OmlineEditor** [comment]
так легче и понятнее. Посмотрите на панель задач на windows. Представьте что иконки будут размазыны по все панели а не сгрупированны.

**Comment by nin-jin** [comment]
Так они и так размазаны:
![image](https://user-images.githubusercontent.com/442988/126055452-e48b47c9-6dd3-4c84-8840-7c682983d893.png)

**Comment by OmlineEditor** [comment]
Они у вас в сам начале сгрупированны, и вот посмотрите как на маке они красиво сидят вместе по центру.

![screen_shot_2013_01_26_at_10_28_19_by_argothar-d5sr7ul](https://user-images.githubusercontent.com/13348933/126070795-df1ffb1d-dc73-4566-8008-e4544d770b31.png)

**Comment by nin-jin** [comment]
Да как-то не очень красиво на мой взгляд.

**Comment by OmlineEditor** [comment]
у нас пока 2 взгляда, один мой, один ваш. нам нужно больше данных (хотя бы 100 человек) для того чтобы принять верное решение.
Может опрос провести?

**Comment by nin-jin** [comment]
Проводите, кто ж запретит.

**Comment by OmlineEditor** [comment]
я уже по знакомым провела, 5 знакомых сказали когда вместе как у вас слева на картинке, 1 сказал что лучше расстояние побольше

**Comment by nin-jin** [comment]
По теме - иконки теперь загружаются исправно?

**Comment by OmlineEditor** [comment]
Через VPN - да, работают. Напрямую без VPN - нет. Проблема где-то у меня, где именно не понятно. т.е. вашей вины нет.
А по поводу сгрупировать иконки если вы **_не_** будите их групировать тогда закрывате тикет, а если захотите сделать более удобный вид, тогда спасибо за реализацию идеи.
