### ISSUE TITLE
wide screen limited only to 1280px

### ISSUE THREAD

**Issue by vfilatov** [hyoo-ru/search.hyoo.ru#14]
On wide screens all the data moved to the left side and limited to 1280px
I think a better design would be either center output or use all of the screen space.
![image](https://user-images.githubusercontent.com/1231330/125648623-fe60705b-b61e-4e21-ac68-61f076482386.png)

**Comment by nin-jin** [comment]
Fixed.

**Comment by vfilatov** [comment]
> Fixed. Try it now.

Excellent!!!

**Comment by nin-jin** [comment]
Would you like to close issue?

**Comment by vfilatov** [comment]
Yes, please do.
It looks perfect now.

Thanks a lot.

**Comment by vfilatov** [comment]
Опять проявилось

**Comment by nin-jin** [comment]
Сейчас результаты открываются в сайдбаре. Как вам такое поведение?

**Comment by vfilatov** [comment]
Да, заметил.
Неожиданное поведение...
На мой вкус лучше в новом окне как раньше.

**Comment by nin-jin** [comment]
Когда что-то активно ищешь при открытии в отдельном окне не удобно, что постоянно теряешь контекст поиска и не можешь просто покликать по результатам в поисках нужного.
С другой стороны, некоторые сайты не хотят открываться во фрейме и их всё-равно приходится открывать в отдельном окне. Кроме того, сейчас заметил, что даже не смотря на атрибут `sandbox` некоторые сайты умудряются выпрыгивать из фрейма. Так что придётся вернуть старую логику, а для случая, когда не хочется терять контекст - можно будет расположить окно с результатом сбоку от окна поиска.

**Comment by vfilatov** [comment]
В нынешней логике конечно есть свои преимущества. Просто непривычно, но это
не значит "неправильно".
Спасибо за полезный проект.
