### ISSUE TITLE
Search engine eat symbol(s).

### ISSUE THREAD

**Issue by Oxyd76** [hyoo-ru/search.hyoo.ru#8]
Hi! I use [qutebrowser](https://github.com/qutebrowser/qutebrowser) in which search engines are configured like this:
```python
set url.searchengines '{"DEFAULT": "https://duckduckgo.com/?q={}", "go": "https://google.com/search?q={}", "hy": "https://search.hyoo.ru/#!query={}"}'
```
And if i put query `"OS/2"` to *DuckDuck Go* or to *Google*, all ok! If i try query to *search.hyoo.ru*, search engine truncate query to `"OS`. But if i try to query this from web interface of *search.hyoo.ru*, all ok and correct response.

**Comment by nin-jin** [comment]
Some browsers incorrectly substitutes query (without url escaping).
Queries for test: `OS/2`, `H&M`
Chrome: incorrect
FF: correct

**Comment by nin-jin** [comment]
I have found the solution - insert question mark to url:

`https://search.hyoo.ru/?#!query={}`

**Comment by Oxyd76** [comment]
> I have found the solution - insert question mark to url:
> 
> `https://search.hyoo.ru/?#!query={}`

It is not worked.
Result url: `https://search.hyoo.ru/#!query=%22OS/2%22` (not worked)
Url via web interface: `https://search.hyoo.ru/#!query=%22OS%2F2%22/2%22` (it works)
Also, for example google's url: `https://www.google.com/search?q=%22OS/2%22`

**Comment by nin-jin** [comment]
You don't insert question mark..

**Comment by Oxyd76** [comment]
> You don't insert question mark..

![2021-07-13_09-43](https://user-images.githubusercontent.com/7885175/125404137-f9d96f00-e3be-11eb-822f-058f61ad12ec.png)
But strange behavior... URL in statusbar visible, and edited with question mark, and yanked without it. All other urls yanked without problems...
Also in another QtWebEngine based browser (falkon) i have similar problem.
![2021-07-13_09-54](https://user-images.githubusercontent.com/7885175/125405728-b3850f80-e3c0-11eb-9465-06aa895195c1.png)

**Comment by Oxyd76** [comment]
Also i test it with / without question mark in latest FF and Brave (chromium based):
FF: Not worked / Not worked
Brave: Not worked / Not worked

**Comment by vfilatov** [comment]
> It is not worked.
> Result url: https://search.hyoo.ru/#!query=%22OS/2%22 (not worked)
It should be URL-encoded
https://search.hyoo.ru/#!query=OS%2F2

**Comment by Oxyd76** [comment]
> What about `H&M` query?

`"H&M"` works in qutebrowser with this result url: [https://search.hyoo.ru/#!query=%22H%26M%22](https://search.hyoo.ru/#!query=%22H%26M%22)

**Comment by nin-jin** [comment]
I have changes separator from `/` to `;` for more compatibility. Try it, please.

**Comment by Oxyd76** [comment]
> I have changed separator from `/` to `;` for more compatibility. Try it, please.

It work's on all tested browsers. Also qutebrowser updated to version 2.3.0 and QtWebEngine updated to v5.15.5 in my distro.

**Comment by nin-jin** [comment]
Cool! Would you like to close tis issue?

**Comment by Oxyd76** [comment]
> Cool! Would you like to close tis issue?

Yep!
