### ISSUE TITLE
Font size on the results page.

### ISSUE THREAD

**Issue by demidovich** [hyoo-ru/search.hyoo.ru#9]
All text on the results page is the same font size. Collection items are not indented. It's uncomfortable to read.

**Comment by nin-jin** [comment]
Fixed font size is the design decision.
What kind of indents and font size would you prefer?

**Comment by demidovich** [comment]
I'm not a designer ) I'm a programmer. 
Maybe the same as Yandex or Google?

**Comment by nin-jin** [comment]
So it's about habits, not usability.

**Comment by demidovich** [comment]
I do not think so. But this is your project. Your rules.

**Comment by demidovich** [comment]
This looks great!

**Comment by nin-jin** [comment]
Would you close this issue?
